#!/bin/sh
/bin/mount -t proc none /proc
/bin/mount -t sysfs sysfs /sys
/bin/mount -t ramfs /tmp
/bin/mount -t ramfs /mnt
/bin/echo > /dev/mdev.seq
/bin/echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
ifconfig eth0 192.168.1.200
#ifconfig eth1 192.168.10.100
route add default gw 192.168.1.2


